spring.application.name=WalletX
spring.datasource.url=jdbc:mysql://localhost:3306/walletx
spring.datasource.username=root
spring.datasource.password=RaheemOlamide123_

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect








